config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :services
  resources :roomrentalmanagers
  resources :roomcheckouts
  resources :pricelists
  resources :paymentmanagements
  resources :room_rental_managers
  resources :room_check_outs
  resources :price_lists
  resources :payment_managements
  resources :guests
  resources :devices
  resources :rooms do
    resources :guests
    resources :devices
  end

  resources :areas do 
      resources :pricelists
  end
  resources :areas do 
    resources :rooms
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: 'rooms#index'
 get "/static_pages/:page", to: "static_pages#show"
 root "static_pages#show", page: "home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
    belongs_to :pricelists
    has_many :rooms
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :room
  
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/paymentmanagement.rb
class Paymentmanagement < ApplicationRecord
  belongs_to :guest
  belongs_to :service
  belongs_to :room
end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
  belongs_to :area
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :area
  has_many :guests
  has_many :devices
end

app/models/roomcheckout.rb
class Roomcheckout < ApplicationRecord
  belongs_to :guest
end

app/models/roomrentalmanager.rb
class Roomrentalmanager < ApplicationRecord
  belongs_to :guest
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
    
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:nameArea, :floor)
    end
end

app/controllers/roomcheckouts_controller.rb
class RoomcheckoutsController < ApplicationController
  before_action :set_roomcheckout, only: [:show, :edit, :update, :destroy]

  # GET /roomcheckouts
  # GET /roomcheckouts.json
  def index
    @roomcheckouts = Roomcheckout.all
  end

  # GET /roomcheckouts/1
  # GET /roomcheckouts/1.json
  def show
  end

  # GET /roomcheckouts/new
  def new
    @roomcheckout = Roomcheckout.new
  end

  # GET /roomcheckouts/1/edit
  def edit
  end

  # POST /roomcheckouts
  # POST /roomcheckouts.json
  def create
    @roomcheckout = Roomcheckout.new(roomcheckout_params)

    respond_to do |format|
      if @roomcheckout.save
        format.html { redirect_to @roomcheckout, notice: 'Roomcheckout was successfully created.' }
        format.json { render :show, status: :created, location: @roomcheckout }
      else
        format.html { render :new }
        format.json { render json: @roomcheckout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roomcheckouts/1
  # PATCH/PUT /roomcheckouts/1.json
  def update
    respond_to do |format|
      if @roomcheckout.update(roomcheckout_params)
        format.html { redirect_to @roomcheckout, notice: 'Roomcheckout was successfully updated.' }
        format.json { render :show, status: :ok, location: @roomcheckout }
      else
        format.html { render :edit }
        format.json { render json: @roomcheckout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roomcheckouts/1
  # DELETE /roomcheckouts/1.json
  def destroy
    @roomcheckout.destroy
    respond_to do |format|
      format.html { redirect_to roomcheckouts_url, notice: 'Roomcheckout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_roomcheckout
      @roomcheckout = Roomcheckout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roomcheckout_params
      params.require(:roomcheckout).permit(:dayRco, :note, :guest_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/helpers/pricelists_helper.rb
module PricelistsHelper
end

app/helpers/room_check_outs_helper.rb
module RoomCheckOutsHelper
end

app/helpers/roomcheckouts_helper.rb
module RoomcheckoutsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/roomcheckouts/_form.html.erb
<%= form_with(model: roomcheckout, local: true) do |form| %>
  <% if roomcheckout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roomcheckout.errors.count, "error") %> prohibited this roomcheckout from being saved:</h2>

      <ul>
      <% roomcheckout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dayRco %>
    <%= form.date_select :dayRco %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :guest_id %>
    <%= form.text_field :guest_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/roomcheckouts/edit.html.erb
<h1>Editing Roomcheckout</h1>

<%= render 'form', roomcheckout: @roomcheckout %>

<%= link_to 'Show', @roomcheckout %> |
<%= link_to 'Back', roomcheckouts_path %>

app/views/roomcheckouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roomcheckouts</h1>

<table>
  <thead>
    <tr>
      <th>Dayrco</th>
      <th>Note</th>
      <th>Guest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roomcheckouts.each do |roomcheckout| %>
      <tr>
        <td><%= roomcheckout.dayRco %></td>
        <td><%= roomcheckout.note %></td>
        <td><%= roomcheckout.guest %></td>
        <td><%= link_to 'Show', roomcheckout %></td>
        <td><%= link_to 'Edit', edit_roomcheckout_path(roomcheckout) %></td>
        <td><%= link_to 'Destroy', roomcheckout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roomcheckout', new_roomcheckout_path %>

app/views/roomcheckouts/new.html.erb
<h1>New Roomcheckout</h1>

<%= render 'form', roomcheckout: @roomcheckout %>

<%= link_to 'Back', roomcheckouts_path %>

app/views/roomcheckouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dayrco:</strong>
  <%= @roomcheckout.dayRco %>
</p>

<p>
  <strong>Note:</strong>
  <%= @roomcheckout.note %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @roomcheckout.guest %>
</p>

<%= link_to 'Edit', edit_roomcheckout_path(@roomcheckout) %> |
<%= link_to 'Back', roomcheckouts_path %>