config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :services
  resources :roomrentalmanagers
  resources :roomcheckouts
  resources :pricelists
  resources :paymentmanagements
  resources :room_rental_managers
  resources :room_check_outs
  resources :price_lists
  resources :payment_managements
  resources :guests
  resources :devices
  resources :rooms do
    resources :guests
    resources :devices
  end

  resources :areas do 
      resources :pricelists
  end
  resources :areas do 
    resources :rooms
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: 'rooms#index'
 get "/static_pages/:page", to: "static_pages#show"
 root "static_pages#show", page: "home"

end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
  belongs_to :area
end

app/controllers/pricelists_controller.rb
class PricelistsController < ApplicationController
  before_action :set_pricelist, only: [:show, :edit, :update, :destroy]

  # GET /pricelists
  # GET /pricelists.json
  def index
    @pricelists = Pricelist.select('*').joins(:area).all
    # @pricelists = ActiveRecord::Base.connection.execute("SELECT * FROM pricelists INNER JOIN areas ON areas.id = pricelists.area_id").to_json
  end

  # GET /pricelists/1
  # GET /pricelists/1.json
  def show
  end

  # GET /pricelists/new
  def new
    @pricelist = Pricelist.new
    @areas = Area.all.map { |a| [a.nameArea, a.id] }
  end

  # GET /pricelists/1/edit
  def edit
  end

  # POST /pricelists
  # POST /pricelists.json
  def create
    @pricelist = Pricelist.new(pricelist_params)

    respond_to do |format|
      if @pricelist.save
        format.html { redirect_to @pricelist, notice: 'Pricelist was successfully created.' }
        format.json { render :show, status: :created, location: @pricelist }
      else
        format.html { render :new }
        format.json { render json: @pricelist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pricelists/1
  # PATCH/PUT /pricelists/1.json
  def update
    respond_to do |format|
      if @pricelist.update(pricelist_params)
        format.html { redirect_to @pricelist, notice: 'Pricelist was successfully updated.' }
        format.json { render :show, status: :ok, location: @pricelist }
      else
        format.html { render :edit }
        format.json { render json: @pricelist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pricelists/1
  # DELETE /pricelists/1.json
  def destroy
    @pricelist.destroy
    respond_to do |format|
      format.html { redirect_to pricelists_url, notice: 'Pricelist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pricelist
      @pricelist = Pricelist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pricelist_params
      params.require(:pricelist).permit(:price, :area_id)
    end
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/helpers/pricelists_helper.rb
module PricelistsHelper
end

app/views/pricelists/_form.html.erb
<%= form_with(model: pricelist, local: true) do |form| %>
  <% if pricelist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pricelist.errors.count, "error") %> prohibited this pricelist from being saved:</h2>

      <ul>
      <% pricelist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :area_id %>
    <%= form.select(:area_id, options_for_select(@areas)) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pricelists/edit.html.erb
<h1>Editing Pricelist</h1>

<%= render 'form', pricelist: @pricelist %>

<%= link_to 'Show', @pricelist %> |
<%= link_to 'Back', pricelists_path %>

app/views/pricelists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pricelists</h1>

<table>
  <thead>
    <tr>
      <th>Price</th>
      <th>Area</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pricelists.each do |pricelist| %>
      <tr>
        <td><%= pricelist.price %></td>
        <td><%= pricelist.area_id %></td>
        <td><%= pricelist.nameArea %></td>
        <td><%= link_to 'Show', pricelist %></td>
        <td><%= link_to 'Edit', edit_pricelist_path(pricelist) %></td>
        <td><%= link_to 'Destroy', pricelist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pricelist', new_pricelist_path %>

app/views/pricelists/new.html.erb
<h1>New Pricelist</h1>

<%= render 'form', pricelist: @pricelist %>

<%= link_to 'Back', pricelists_path %>

app/views/pricelists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Price:</strong>
  <%= @pricelist.price %>
</p>

<p>
  <strong>Area:</strong>
  <%= @pricelist.area %>
</p>

<%= link_to 'Edit', edit_pricelist_path(@pricelist) %> |
<%= link_to 'Back', pricelists_path %>