config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :services
  resources :roomrentalmanagers
  resources :roomcheckouts
  resources :pricelists
  resources :paymentmanagements
  resources :room_rental_managers
  resources :room_check_outs
  resources :price_lists
  resources :payment_managements
  resources :guests
  resources :devices
  resources :rooms do
    resources :guests
    resources :devices
  end

  resources :areas do 
      resources :pricelists
  end
  resources :areas do 
    resources :rooms
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: 'rooms#index'
 get "/static_pages/:page", to: "static_pages#show"
 root "static_pages#show", page: "home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
    belongs_to :pricelists
    has_many :rooms
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :room
  
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/paymentmanagement.rb
class Paymentmanagement < ApplicationRecord
  belongs_to :guest
  belongs_to :service
  belongs_to :room
end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
  belongs_to :area
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :area
  has_many :guests
  has_many :devices
end

app/models/roomcheckout.rb
class Roomcheckout < ApplicationRecord
  belongs_to :guest
end

app/models/roomrentalmanager.rb
class Roomrentalmanager < ApplicationRecord
  belongs_to :guest
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
    
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:nameArea, :floor)
    end
end

app/controllers/paymentmanagements_controller.rb
class PaymentmanagementsController < ApplicationController
  before_action :set_paymentmanagement, only: [:show, :edit, :update, :destroy]

  # GET /paymentmanagements
  # GET /paymentmanagements.json
  def index
    @paymentmanagements = Paymentmanagement.all
  end

  # GET /paymentmanagements/1
  # GET /paymentmanagements/1.json
  def show
  end

  # GET /paymentmanagements/new
  def new
    @paymentmanagement = Paymentmanagement.new
  end

  # GET /paymentmanagements/1/edit
  def edit
  end

  # POST /paymentmanagements
  # POST /paymentmanagements.json
  def create
    @paymentmanagement = Paymentmanagement.new(paymentmanagement_params)

    respond_to do |format|
      if @paymentmanagement.save
        format.html { redirect_to @paymentmanagement, notice: 'Paymentmanagement was successfully created.' }
        format.json { render :show, status: :created, location: @paymentmanagement }
      else
        format.html { render :new }
        format.json { render json: @paymentmanagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paymentmanagements/1
  # PATCH/PUT /paymentmanagements/1.json
  def update
    respond_to do |format|
      if @paymentmanagement.update(paymentmanagement_params)
        format.html { redirect_to @paymentmanagement, notice: 'Paymentmanagement was successfully updated.' }
        format.json { render :show, status: :ok, location: @paymentmanagement }
      else
        format.html { render :edit }
        format.json { render json: @paymentmanagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paymentmanagements/1
  # DELETE /paymentmanagements/1.json
  def destroy
    @paymentmanagement.destroy
    respond_to do |format|
      format.html { redirect_to paymentmanagements_url, notice: 'Paymentmanagement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paymentmanagement
      @paymentmanagement = Paymentmanagement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paymentmanagement_params
      params.require(:paymentmanagement).permit(:dayPM, :guest_id, :service_id, :room_id, :electricity, :internet, :water, :roomPrice, :debt)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/payment_managements_helper.rb
module PaymentManagementsHelper
end

app/helpers/paymentmanagements_helper.rb
module PaymentmanagementsHelper
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/helpers/pricelists_helper.rb
module PricelistsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/paymentmanagements/_form.html.erb
<%= form_with(model: paymentmanagement, local: true) do |form| %>
  <% if paymentmanagement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(paymentmanagement.errors.count, "error") %> prohibited this paymentmanagement from being saved:</h2>

      <ul>
      <% paymentmanagement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dayPM %>
    <%= form.date_select :dayPM %>
  </div>

  <div class="field">
    <%= form.label :guest_id %>
    <%= form.text_field :guest_id %>
  </div>

  <div class="field">
    <%= form.label :service_id %>
    <%= form.text_field :service_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.select(:room_id, options_for_select(@rooms)) %>
  </div>

  <div class="field">
    <%= form.label :electricity %>
    <%= form.number_field :electricity %>
  </div>

  <div class="field">
    <%= form.label :internet %>
    <%= form.number_field :internet %>
  </div>

  <div class="field">
    <%= form.label :water %>
    <%= form.number_field :water %>
  </div>

  <div class="field">
    <%= form.label :roomPrice %>
    <%= form.number_field :roomPrice %>
  </div>

  <div class="field">
    <%= form.label :debt %>
    <%= form.number_field :debt %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/paymentmanagements/edit.html.erb
<h1>Editing Paymentmanagement</h1>

<%= render 'form', paymentmanagement: @paymentmanagement %>

<%= link_to 'Show', @paymentmanagement %> |
<%= link_to 'Back', paymentmanagements_path %>

app/views/paymentmanagements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Paymentmanagements</h1>

<table>
  <thead>
    <tr>
      <th>Daypm</th>
      <th>Guest</th>
      <th>Service</th>
      <th>Room</th>
      <th>Electricity</th>
      <th>Internet</th>
      <th>Water</th>
      <th>Roomprice</th>
      <th>Debt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paymentmanagements.each do |paymentmanagement| %>
      <tr>
        <td><%= paymentmanagement.dayPM %></td>
        <td><%= paymentmanagement.guest %></td>
        <td><%= paymentmanagement.service %></td>
        <td><%= paymentmanagement.room %></td>
        <td><%= paymentmanagement.electricity %></td>
        <td><%= paymentmanagement.internet %></td>
        <td><%= paymentmanagement.water %></td>
        <td><%= paymentmanagement.roomPrice %></td>
        <td><%= paymentmanagement.debt %></td>
        <td><%= link_to 'Show', paymentmanagement %></td>
        <td><%= link_to 'Edit', edit_paymentmanagement_path(paymentmanagement) %></td>
        <td><%= link_to 'Destroy', paymentmanagement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paymentmanagement', new_paymentmanagement_path %>

app/views/paymentmanagements/new.html.erb
<h1>New Paymentmanagement</h1>

<%= render 'form', paymentmanagement: @paymentmanagement %>

<%= link_to 'Back', paymentmanagements_path %>

app/views/paymentmanagements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Daypm:</strong>
  <%= @paymentmanagement.dayPM %>
</p>

<p>
  <strong>Guest:</strong>
  <%= @paymentmanagement.guest %>
</p>

<p>
  <strong>Service:</strong>
  <%= @paymentmanagement.service %>
</p>

<p>
  <strong>Room:</strong>
  <%= @paymentmanagement.room %>
</p>

<p>
  <strong>Electricity:</strong>
  <%= @paymentmanagement.electricity %>
</p>

<p>
  <strong>Internet:</strong>
  <%= @paymentmanagement.internet %>
</p>

<p>
  <strong>Water:</strong>
  <%= @paymentmanagement.water %>
</p>

<p>
  <strong>Roomprice:</strong>
  <%= @paymentmanagement.roomPrice %>
</p>

<p>
  <strong>Debt:</strong>
  <%= @paymentmanagement.debt %>
</p>

<%= link_to 'Edit', edit_paymentmanagement_path(@paymentmanagement) %> |
<%= link_to 'Back', paymentmanagements_path %>