config/routes.rb
Rails.application.routes.draw do

  resources :areas
  resources :services
  resources :roomrentalmanagers
  resources :roomcheckouts
  resources :pricelists
  resources :paymentmanagements
  resources :room_rental_managers
  resources :room_check_outs
  resources :price_lists
  resources :payment_managements
  resources :guests
  resources :devices
  resources :rooms do
    resources :guests
    resources :devices
  end

  resources :areas do 
      resources :pricelists
  end
  resources :areas do 
    resources :rooms
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,controllers: {sessions: 'users/sessions'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#  root to: 'rooms#index'
 get "/static_pages/:page", to: "static_pages#show"
 root "static_pages#show", page: "home"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
    belongs_to :pricelists
    has_many :rooms
end

app/models/device.rb
class Device < ApplicationRecord
  belongs_to :room
  
end

app/models/guest.rb
class Guest < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/paymentmanagement.rb
class Paymentmanagement < ApplicationRecord
  belongs_to :guest
  belongs_to :service
  belongs_to :room
end

app/models/pricelist.rb
class Pricelist < ApplicationRecord
  belongs_to :area
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :area
  has_many :guests
  has_many :devices
end

app/models/roomcheckout.rb
class Roomcheckout < ApplicationRecord
  belongs_to :guest
end

app/models/roomrentalmanager.rb
class Roomrentalmanager < ApplicationRecord
  belongs_to :guest
end

app/models/service.rb
class Service < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :set_area, only: [:show, :edit, :update, :destroy]

  # GET /areas
  # GET /areas.json
  def index
    @areas = Area.all
    
  end

  # GET /areas/1
  # GET /areas/1.json
  def show
  end

  # GET /areas/new
  def new
    @area = Area.new
  end

  # GET /areas/1/edit
  def edit
  end

  # POST /areas
  # POST /areas.json
  def create
    @area = Area.new(area_params)

    respond_to do |format|
      if @area.save
        format.html { redirect_to @area, notice: 'Area was successfully created.' }
        format.json { render :show, status: :created, location: @area }
      else
        format.html { render :new }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /areas/1
  # PATCH/PUT /areas/1.json
  def update
    respond_to do |format|
      if @area.update(area_params)
        format.html { redirect_to @area, notice: 'Area was successfully updated.' }
        format.json { render :show, status: :ok, location: @area }
      else
        format.html { render :edit }
        format.json { render json: @area.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /areas/1
  # DELETE /areas/1.json
  def destroy
    @area.destroy
    respond_to do |format|
      format.html { redirect_to areas_url, notice: 'Area was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_area
      @area = Area.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def area_params
      params.require(:area).permit(:nameArea, :floor)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.select('rooms.id ,rooms.nameRoom, rooms.maxSlot, rooms.statusRoom, rooms.numOfPeople, rooms.area_id,areas.nameArea').joins(:area).all
    
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show

  end

  # GET /rooms/new
  def new

    @areas = Area.all.map { |a| [a.nameArea, a.id] }


      @room = Room.new



  end

  # GET /rooms/1/edit
  def edit
    @areas = Area.all.map { |a| [a.nameArea, a.id] }
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
@room.nameRoom='Phòng ' + @room.nameRoom
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update

    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:nameRoom, :maxSlot, :statusRoom, :numOfPeople, :area_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/price_lists_helper.rb
module PriceListsHelper
end

app/helpers/pricelists_helper.rb
module PricelistsHelper
end

app/helpers/roomcheckouts_helper.rb
module RoomcheckoutsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/areas/_form.html.erb
<%= form_with(model: area, local: true) do |form| %>
  <% if area.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(area.errors.count, "error") %> prohibited this area from being saved:</h2>

      <ul>
      <% area.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nameArea %>
    <%= form.text_field :nameArea %>
  </div>

  <div class="field">
    <%= form.label :floor %>
    <%= form.number_field :floor %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/areas/edit.html.erb
<h1>Editing Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Show', @area %> |
<%= link_to 'Back', areas_path %>

app/views/areas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Areas</h1>

<table>
  <thead>
    <tr>
      <th>Namearea</th>
      <th>Floor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @areas.each do |area| %>
      <tr>
        <td><%= area.nameArea %></td>
        <td><%= area.floor %></td>
        <td><%= link_to 'Show', area %></td>
        <td><%= link_to 'Edit', edit_area_path(area) %></td>
        <td><%= link_to 'Destroy', area, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Area', new_area_path %>

app/views/areas/new.html.erb
<h1>New Area</h1>

<%= render 'form', area: @area %>

<%= link_to 'Back', areas_path %>

app/views/areas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Namearea:</strong>
  <%= @area.nameArea %>
</p>

<p>
  <strong>Floor:</strong>
  <%= @area.floor %>
</p>

<%= link_to 'Edit', edit_area_path(@area) %> |
<%= link_to 'Back', areas_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nameRoom %>
    <%= form.text_field :nameRoom %>
  </div>

  <div class="field">
    <%= form.label :maxSlot %>
    <%= form.number_field :maxSlot %>
  </div>

  <div class="field">
    <%= form.label :statusRoom %>
    <%= form.text_field :statusRoom %>
  </div>

  <div class="field">
    <%= form.label :numOfPeople %>
    <%= form.number_field :numOfPeople %>
  </div>

  <div class="field">
    <%= form.label :area_id %>
    <%= form.select(:area_id, options_for_select(@areas)) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Nameroom</th>
      <th>Maxslot</th>
      <th>Statusroom</th>
      <th>Numofpeople</th>
      <th>Area Name</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.nameRoom %></td>
        <td><%= room.maxSlot %></td>
        <td><%= room.statusRoom %></td>
        <td><%= room.numOfPeople %></td>
        <td><%= room.nameArea %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to "List Guests", room_guests_path(room.id) %></td>
        <td><%= link_to "List Devices", room_devices_path(room.id) %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%#= render 'form', room: @room %>
<%= form_with(model: @room, local: true) do |form| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% @room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nameRoom %>
    <%= form.text_field :nameRoom %>
  </div>

  <div class="field">
    <%= form.label :maxSlot %>
    <%= form.number_field :maxSlot %>
  </div>

  <div class="field">
    <%= form.label :statusRoom %>
    <%= form.text_field :statusRoom %>
  </div>

  <div class="field">
    <%= form.label :numOfPeople %>
    <%= form.number_field :numOfPeople %>
  </div>

  <div class="field">
    <%= form.label :area_id %>
    <%= form.select(:area_id, options_for_select(@areas)) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nameroom:</strong>
  <%= @room.nameRoom %>
</p>

<p>
  <strong>Maxslot:</strong>
  <%= @room.maxSlot %>
</p>

<p>
  <strong>Statusroom:</strong>
  <%= @room.statusRoom %>
</p>

<p>
  <strong>Numofpeople:</strong>
  <%= @room.numOfPeople %>
</p>

<p>
  <strong>Area:</strong>
  <%= @room.area.nameArea %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>